# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /var/tmp/taxator-tk-stable

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /var/tmp/taxator-tk-stable

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /var/tmp/taxator-tk-stable/CMakeFiles /var/tmp/taxator-tk-stable/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /var/tmp/taxator-tk-stable/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named acc2taxid

# Build rule for target.
acc2taxid: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 acc2taxid
.PHONY : acc2taxid

# fast build rule for target.
acc2taxid/fast:
	$(MAKE) -f CMakeFiles/acc2taxid.dir/build.make CMakeFiles/acc2taxid.dir/build
.PHONY : acc2taxid/fast

#=============================================================================
# Target rules for targets named alignments-prefilter

# Build rule for target.
alignments-prefilter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 alignments-prefilter
.PHONY : alignments-prefilter

# fast build rule for target.
alignments-prefilter/fast:
	$(MAKE) -f CMakeFiles/alignments-prefilter.dir/build.make CMakeFiles/alignments-prefilter.dir/build
.PHONY : alignments-prefilter/fast

#=============================================================================
# Target rules for targets named alignments-prefilter-training

# Build rule for target.
alignments-prefilter-training: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 alignments-prefilter-training
.PHONY : alignments-prefilter-training

# fast build rule for target.
alignments-prefilter-training/fast:
	$(MAKE) -f CMakeFiles/alignments-prefilter-training.dir/build.make CMakeFiles/alignments-prefilter-training.dir/build
.PHONY : alignments-prefilter-training/fast

#=============================================================================
# Target rules for targets named extract-fastacomment-ncbifield

# Build rule for target.
extract-fastacomment-ncbifield: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 extract-fastacomment-ncbifield
.PHONY : extract-fastacomment-ncbifield

# fast build rule for target.
extract-fastacomment-ncbifield/fast:
	$(MAKE) -f CMakeFiles/extract-fastacomment-ncbifield.dir/build.make CMakeFiles/extract-fastacomment-ncbifield.dir/build
.PHONY : extract-fastacomment-ncbifield/fast

#=============================================================================
# Target rules for targets named name-filter

# Build rule for target.
name-filter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 name-filter
.PHONY : name-filter

# fast build rule for target.
name-filter/fast:
	$(MAKE) -f CMakeFiles/name-filter.dir/build.make CMakeFiles/name-filter.dir/build
.PHONY : name-filter/fast

#=============================================================================
# Target rules for targets named prediction-error

# Build rule for target.
prediction-error: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prediction-error
.PHONY : prediction-error

# fast build rule for target.
prediction-error/fast:
	$(MAKE) -f CMakeFiles/prediction-error.dir/build.make CMakeFiles/prediction-error.dir/build
.PHONY : prediction-error/fast

#=============================================================================
# Target rules for targets named prediction2distances

# Build rule for target.
prediction2distances: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prediction2distances
.PHONY : prediction2distances

# fast build rule for target.
prediction2distances/fast:
	$(MAKE) -f CMakeFiles/prediction2distances.dir/build.make CMakeFiles/prediction2distances.dir/build
.PHONY : prediction2distances/fast

#=============================================================================
# Target rules for targets named predictor

# Build rule for target.
predictor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 predictor
.PHONY : predictor

# fast build rule for target.
predictor/fast:
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/build
.PHONY : predictor/fast

#=============================================================================
# Target rules for targets named rank-filter

# Build rule for target.
rank-filter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rank-filter
.PHONY : rank-filter

# fast build rule for target.
rank-filter/fast:
	$(MAKE) -f CMakeFiles/rank-filter.dir/build.make CMakeFiles/rank-filter.dir/build
.PHONY : rank-filter/fast

#=============================================================================
# Target rules for targets named unittest_ncbitaxonomy

# Build rule for target.
unittest_ncbitaxonomy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unittest_ncbitaxonomy
.PHONY : unittest_ncbitaxonomy

# fast build rule for target.
unittest_ncbitaxonomy/fast:
	$(MAKE) -f CMakeFiles/unittest_ncbitaxonomy.dir/build.make CMakeFiles/unittest_ncbitaxonomy.dir/build
.PHONY : unittest_ncbitaxonomy/fast

acc2taxid.o: acc2taxid.cpp.o
.PHONY : acc2taxid.o

# target to build an object file
acc2taxid.cpp.o:
	$(MAKE) -f CMakeFiles/acc2taxid.dir/build.make CMakeFiles/acc2taxid.dir/acc2taxid.cpp.o
.PHONY : acc2taxid.cpp.o

acc2taxid.i: acc2taxid.cpp.i
.PHONY : acc2taxid.i

# target to preprocess a source file
acc2taxid.cpp.i:
	$(MAKE) -f CMakeFiles/acc2taxid.dir/build.make CMakeFiles/acc2taxid.dir/acc2taxid.cpp.i
.PHONY : acc2taxid.cpp.i

acc2taxid.s: acc2taxid.cpp.s
.PHONY : acc2taxid.s

# target to generate assembly for a file
acc2taxid.cpp.s:
	$(MAKE) -f CMakeFiles/acc2taxid.dir/build.make CMakeFiles/acc2taxid.dir/acc2taxid.cpp.s
.PHONY : acc2taxid.cpp.s

alignments-prefilter-training.o: alignments-prefilter-training.cpp.o
.PHONY : alignments-prefilter-training.o

# target to build an object file
alignments-prefilter-training.cpp.o:
	$(MAKE) -f CMakeFiles/alignments-prefilter-training.dir/build.make CMakeFiles/alignments-prefilter-training.dir/alignments-prefilter-training.cpp.o
.PHONY : alignments-prefilter-training.cpp.o

alignments-prefilter-training.i: alignments-prefilter-training.cpp.i
.PHONY : alignments-prefilter-training.i

# target to preprocess a source file
alignments-prefilter-training.cpp.i:
	$(MAKE) -f CMakeFiles/alignments-prefilter-training.dir/build.make CMakeFiles/alignments-prefilter-training.dir/alignments-prefilter-training.cpp.i
.PHONY : alignments-prefilter-training.cpp.i

alignments-prefilter-training.s: alignments-prefilter-training.cpp.s
.PHONY : alignments-prefilter-training.s

# target to generate assembly for a file
alignments-prefilter-training.cpp.s:
	$(MAKE) -f CMakeFiles/alignments-prefilter-training.dir/build.make CMakeFiles/alignments-prefilter-training.dir/alignments-prefilter-training.cpp.s
.PHONY : alignments-prefilter-training.cpp.s

alignments-prefilter.o: alignments-prefilter.cpp.o
.PHONY : alignments-prefilter.o

# target to build an object file
alignments-prefilter.cpp.o:
	$(MAKE) -f CMakeFiles/alignments-prefilter.dir/build.make CMakeFiles/alignments-prefilter.dir/alignments-prefilter.cpp.o
.PHONY : alignments-prefilter.cpp.o

alignments-prefilter.i: alignments-prefilter.cpp.i
.PHONY : alignments-prefilter.i

# target to preprocess a source file
alignments-prefilter.cpp.i:
	$(MAKE) -f CMakeFiles/alignments-prefilter.dir/build.make CMakeFiles/alignments-prefilter.dir/alignments-prefilter.cpp.i
.PHONY : alignments-prefilter.cpp.i

alignments-prefilter.s: alignments-prefilter.cpp.s
.PHONY : alignments-prefilter.s

# target to generate assembly for a file
alignments-prefilter.cpp.s:
	$(MAKE) -f CMakeFiles/alignments-prefilter.dir/build.make CMakeFiles/alignments-prefilter.dir/alignments-prefilter.cpp.s
.PHONY : alignments-prefilter.cpp.s

extract-fastacomment-ncbifield.o: extract-fastacomment-ncbifield.cpp.o
.PHONY : extract-fastacomment-ncbifield.o

# target to build an object file
extract-fastacomment-ncbifield.cpp.o:
	$(MAKE) -f CMakeFiles/extract-fastacomment-ncbifield.dir/build.make CMakeFiles/extract-fastacomment-ncbifield.dir/extract-fastacomment-ncbifield.cpp.o
.PHONY : extract-fastacomment-ncbifield.cpp.o

extract-fastacomment-ncbifield.i: extract-fastacomment-ncbifield.cpp.i
.PHONY : extract-fastacomment-ncbifield.i

# target to preprocess a source file
extract-fastacomment-ncbifield.cpp.i:
	$(MAKE) -f CMakeFiles/extract-fastacomment-ncbifield.dir/build.make CMakeFiles/extract-fastacomment-ncbifield.dir/extract-fastacomment-ncbifield.cpp.i
.PHONY : extract-fastacomment-ncbifield.cpp.i

extract-fastacomment-ncbifield.s: extract-fastacomment-ncbifield.cpp.s
.PHONY : extract-fastacomment-ncbifield.s

# target to generate assembly for a file
extract-fastacomment-ncbifield.cpp.s:
	$(MAKE) -f CMakeFiles/extract-fastacomment-ncbifield.dir/build.make CMakeFiles/extract-fastacomment-ncbifield.dir/extract-fastacomment-ncbifield.cpp.s
.PHONY : extract-fastacomment-ncbifield.cpp.s

name-filter.o: name-filter.cpp.o
.PHONY : name-filter.o

# target to build an object file
name-filter.cpp.o:
	$(MAKE) -f CMakeFiles/name-filter.dir/build.make CMakeFiles/name-filter.dir/name-filter.cpp.o
.PHONY : name-filter.cpp.o

name-filter.i: name-filter.cpp.i
.PHONY : name-filter.i

# target to preprocess a source file
name-filter.cpp.i:
	$(MAKE) -f CMakeFiles/name-filter.dir/build.make CMakeFiles/name-filter.dir/name-filter.cpp.i
.PHONY : name-filter.cpp.i

name-filter.s: name-filter.cpp.s
.PHONY : name-filter.s

# target to generate assembly for a file
name-filter.cpp.s:
	$(MAKE) -f CMakeFiles/name-filter.dir/build.make CMakeFiles/name-filter.dir/name-filter.cpp.s
.PHONY : name-filter.cpp.s

prediction-error.o: prediction-error.cpp.o
.PHONY : prediction-error.o

# target to build an object file
prediction-error.cpp.o:
	$(MAKE) -f CMakeFiles/prediction-error.dir/build.make CMakeFiles/prediction-error.dir/prediction-error.cpp.o
.PHONY : prediction-error.cpp.o

prediction-error.i: prediction-error.cpp.i
.PHONY : prediction-error.i

# target to preprocess a source file
prediction-error.cpp.i:
	$(MAKE) -f CMakeFiles/prediction-error.dir/build.make CMakeFiles/prediction-error.dir/prediction-error.cpp.i
.PHONY : prediction-error.cpp.i

prediction-error.s: prediction-error.cpp.s
.PHONY : prediction-error.s

# target to generate assembly for a file
prediction-error.cpp.s:
	$(MAKE) -f CMakeFiles/prediction-error.dir/build.make CMakeFiles/prediction-error.dir/prediction-error.cpp.s
.PHONY : prediction-error.cpp.s

prediction2distances.o: prediction2distances.cpp.o
.PHONY : prediction2distances.o

# target to build an object file
prediction2distances.cpp.o:
	$(MAKE) -f CMakeFiles/prediction2distances.dir/build.make CMakeFiles/prediction2distances.dir/prediction2distances.cpp.o
.PHONY : prediction2distances.cpp.o

prediction2distances.i: prediction2distances.cpp.i
.PHONY : prediction2distances.i

# target to preprocess a source file
prediction2distances.cpp.i:
	$(MAKE) -f CMakeFiles/prediction2distances.dir/build.make CMakeFiles/prediction2distances.dir/prediction2distances.cpp.i
.PHONY : prediction2distances.cpp.i

prediction2distances.s: prediction2distances.cpp.s
.PHONY : prediction2distances.s

# target to generate assembly for a file
prediction2distances.cpp.s:
	$(MAKE) -f CMakeFiles/prediction2distances.dir/build.make CMakeFiles/prediction2distances.dir/prediction2distances.cpp.s
.PHONY : prediction2distances.cpp.s

predictor.o: predictor.cpp.o
.PHONY : predictor.o

# target to build an object file
predictor.cpp.o:
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/predictor.cpp.o
.PHONY : predictor.cpp.o

predictor.i: predictor.cpp.i
.PHONY : predictor.i

# target to preprocess a source file
predictor.cpp.i:
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/predictor.cpp.i
.PHONY : predictor.cpp.i

predictor.s: predictor.cpp.s
.PHONY : predictor.s

# target to generate assembly for a file
predictor.cpp.s:
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/predictor.cpp.s
.PHONY : predictor.cpp.s

rank-filter.o: rank-filter.cpp.o
.PHONY : rank-filter.o

# target to build an object file
rank-filter.cpp.o:
	$(MAKE) -f CMakeFiles/rank-filter.dir/build.make CMakeFiles/rank-filter.dir/rank-filter.cpp.o
.PHONY : rank-filter.cpp.o

rank-filter.i: rank-filter.cpp.i
.PHONY : rank-filter.i

# target to preprocess a source file
rank-filter.cpp.i:
	$(MAKE) -f CMakeFiles/rank-filter.dir/build.make CMakeFiles/rank-filter.dir/rank-filter.cpp.i
.PHONY : rank-filter.cpp.i

rank-filter.s: rank-filter.cpp.s
.PHONY : rank-filter.s

# target to generate assembly for a file
rank-filter.cpp.s:
	$(MAKE) -f CMakeFiles/rank-filter.dir/build.make CMakeFiles/rank-filter.dir/rank-filter.cpp.s
.PHONY : rank-filter.cpp.s

src/accessconv.o: src/accessconv.cpp.o
.PHONY : src/accessconv.o

# target to build an object file
src/accessconv.cpp.o:
	$(MAKE) -f CMakeFiles/acc2taxid.dir/build.make CMakeFiles/acc2taxid.dir/src/accessconv.cpp.o
	$(MAKE) -f CMakeFiles/alignments-prefilter-training.dir/build.make CMakeFiles/alignments-prefilter-training.dir/src/accessconv.cpp.o
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/src/accessconv.cpp.o
	$(MAKE) -f CMakeFiles/unittest_ncbitaxonomy.dir/build.make CMakeFiles/unittest_ncbitaxonomy.dir/src/accessconv.cpp.o
.PHONY : src/accessconv.cpp.o

src/accessconv.i: src/accessconv.cpp.i
.PHONY : src/accessconv.i

# target to preprocess a source file
src/accessconv.cpp.i:
	$(MAKE) -f CMakeFiles/acc2taxid.dir/build.make CMakeFiles/acc2taxid.dir/src/accessconv.cpp.i
	$(MAKE) -f CMakeFiles/alignments-prefilter-training.dir/build.make CMakeFiles/alignments-prefilter-training.dir/src/accessconv.cpp.i
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/src/accessconv.cpp.i
	$(MAKE) -f CMakeFiles/unittest_ncbitaxonomy.dir/build.make CMakeFiles/unittest_ncbitaxonomy.dir/src/accessconv.cpp.i
.PHONY : src/accessconv.cpp.i

src/accessconv.s: src/accessconv.cpp.s
.PHONY : src/accessconv.s

# target to generate assembly for a file
src/accessconv.cpp.s:
	$(MAKE) -f CMakeFiles/acc2taxid.dir/build.make CMakeFiles/acc2taxid.dir/src/accessconv.cpp.s
	$(MAKE) -f CMakeFiles/alignments-prefilter-training.dir/build.make CMakeFiles/alignments-prefilter-training.dir/src/accessconv.cpp.s
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/src/accessconv.cpp.s
	$(MAKE) -f CMakeFiles/unittest_ncbitaxonomy.dir/build.make CMakeFiles/unittest_ncbitaxonomy.dir/src/accessconv.cpp.s
.PHONY : src/accessconv.cpp.s

src/alignmentrecord.o: src/alignmentrecord.cpp.o
.PHONY : src/alignmentrecord.o

# target to build an object file
src/alignmentrecord.cpp.o:
	$(MAKE) -f CMakeFiles/alignments-prefilter.dir/build.make CMakeFiles/alignments-prefilter.dir/src/alignmentrecord.cpp.o
	$(MAKE) -f CMakeFiles/alignments-prefilter-training.dir/build.make CMakeFiles/alignments-prefilter-training.dir/src/alignmentrecord.cpp.o
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/src/alignmentrecord.cpp.o
.PHONY : src/alignmentrecord.cpp.o

src/alignmentrecord.i: src/alignmentrecord.cpp.i
.PHONY : src/alignmentrecord.i

# target to preprocess a source file
src/alignmentrecord.cpp.i:
	$(MAKE) -f CMakeFiles/alignments-prefilter.dir/build.make CMakeFiles/alignments-prefilter.dir/src/alignmentrecord.cpp.i
	$(MAKE) -f CMakeFiles/alignments-prefilter-training.dir/build.make CMakeFiles/alignments-prefilter-training.dir/src/alignmentrecord.cpp.i
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/src/alignmentrecord.cpp.i
.PHONY : src/alignmentrecord.cpp.i

src/alignmentrecord.s: src/alignmentrecord.cpp.s
.PHONY : src/alignmentrecord.s

# target to generate assembly for a file
src/alignmentrecord.cpp.s:
	$(MAKE) -f CMakeFiles/alignments-prefilter.dir/build.make CMakeFiles/alignments-prefilter.dir/src/alignmentrecord.cpp.s
	$(MAKE) -f CMakeFiles/alignments-prefilter-training.dir/build.make CMakeFiles/alignments-prefilter-training.dir/src/alignmentrecord.cpp.s
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/src/alignmentrecord.cpp.s
.PHONY : src/alignmentrecord.cpp.s

src/ncbidata.o: src/ncbidata.cpp.o
.PHONY : src/ncbidata.o

# target to build an object file
src/ncbidata.cpp.o:
	$(MAKE) -f CMakeFiles/alignments-prefilter-training.dir/build.make CMakeFiles/alignments-prefilter-training.dir/src/ncbidata.cpp.o
	$(MAKE) -f CMakeFiles/extract-fastacomment-ncbifield.dir/build.make CMakeFiles/extract-fastacomment-ncbifield.dir/src/ncbidata.cpp.o
	$(MAKE) -f CMakeFiles/name-filter.dir/build.make CMakeFiles/name-filter.dir/src/ncbidata.cpp.o
	$(MAKE) -f CMakeFiles/prediction2distances.dir/build.make CMakeFiles/prediction2distances.dir/src/ncbidata.cpp.o
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/src/ncbidata.cpp.o
	$(MAKE) -f CMakeFiles/rank-filter.dir/build.make CMakeFiles/rank-filter.dir/src/ncbidata.cpp.o
	$(MAKE) -f CMakeFiles/unittest_ncbitaxonomy.dir/build.make CMakeFiles/unittest_ncbitaxonomy.dir/src/ncbidata.cpp.o
.PHONY : src/ncbidata.cpp.o

src/ncbidata.i: src/ncbidata.cpp.i
.PHONY : src/ncbidata.i

# target to preprocess a source file
src/ncbidata.cpp.i:
	$(MAKE) -f CMakeFiles/alignments-prefilter-training.dir/build.make CMakeFiles/alignments-prefilter-training.dir/src/ncbidata.cpp.i
	$(MAKE) -f CMakeFiles/extract-fastacomment-ncbifield.dir/build.make CMakeFiles/extract-fastacomment-ncbifield.dir/src/ncbidata.cpp.i
	$(MAKE) -f CMakeFiles/name-filter.dir/build.make CMakeFiles/name-filter.dir/src/ncbidata.cpp.i
	$(MAKE) -f CMakeFiles/prediction2distances.dir/build.make CMakeFiles/prediction2distances.dir/src/ncbidata.cpp.i
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/src/ncbidata.cpp.i
	$(MAKE) -f CMakeFiles/rank-filter.dir/build.make CMakeFiles/rank-filter.dir/src/ncbidata.cpp.i
	$(MAKE) -f CMakeFiles/unittest_ncbitaxonomy.dir/build.make CMakeFiles/unittest_ncbitaxonomy.dir/src/ncbidata.cpp.i
.PHONY : src/ncbidata.cpp.i

src/ncbidata.s: src/ncbidata.cpp.s
.PHONY : src/ncbidata.s

# target to generate assembly for a file
src/ncbidata.cpp.s:
	$(MAKE) -f CMakeFiles/alignments-prefilter-training.dir/build.make CMakeFiles/alignments-prefilter-training.dir/src/ncbidata.cpp.s
	$(MAKE) -f CMakeFiles/extract-fastacomment-ncbifield.dir/build.make CMakeFiles/extract-fastacomment-ncbifield.dir/src/ncbidata.cpp.s
	$(MAKE) -f CMakeFiles/name-filter.dir/build.make CMakeFiles/name-filter.dir/src/ncbidata.cpp.s
	$(MAKE) -f CMakeFiles/prediction2distances.dir/build.make CMakeFiles/prediction2distances.dir/src/ncbidata.cpp.s
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/src/ncbidata.cpp.s
	$(MAKE) -f CMakeFiles/rank-filter.dir/build.make CMakeFiles/rank-filter.dir/src/ncbidata.cpp.s
	$(MAKE) -f CMakeFiles/unittest_ncbitaxonomy.dir/build.make CMakeFiles/unittest_ncbitaxonomy.dir/src/ncbidata.cpp.s
.PHONY : src/ncbidata.cpp.s

src/sqlite3pp.o: src/sqlite3pp.cpp.o
.PHONY : src/sqlite3pp.o

# target to build an object file
src/sqlite3pp.cpp.o:
	$(MAKE) -f CMakeFiles/acc2taxid.dir/build.make CMakeFiles/acc2taxid.dir/src/sqlite3pp.cpp.o
	$(MAKE) -f CMakeFiles/alignments-prefilter-training.dir/build.make CMakeFiles/alignments-prefilter-training.dir/src/sqlite3pp.cpp.o
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/src/sqlite3pp.cpp.o
	$(MAKE) -f CMakeFiles/unittest_ncbitaxonomy.dir/build.make CMakeFiles/unittest_ncbitaxonomy.dir/src/sqlite3pp.cpp.o
.PHONY : src/sqlite3pp.cpp.o

src/sqlite3pp.i: src/sqlite3pp.cpp.i
.PHONY : src/sqlite3pp.i

# target to preprocess a source file
src/sqlite3pp.cpp.i:
	$(MAKE) -f CMakeFiles/acc2taxid.dir/build.make CMakeFiles/acc2taxid.dir/src/sqlite3pp.cpp.i
	$(MAKE) -f CMakeFiles/alignments-prefilter-training.dir/build.make CMakeFiles/alignments-prefilter-training.dir/src/sqlite3pp.cpp.i
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/src/sqlite3pp.cpp.i
	$(MAKE) -f CMakeFiles/unittest_ncbitaxonomy.dir/build.make CMakeFiles/unittest_ncbitaxonomy.dir/src/sqlite3pp.cpp.i
.PHONY : src/sqlite3pp.cpp.i

src/sqlite3pp.s: src/sqlite3pp.cpp.s
.PHONY : src/sqlite3pp.s

# target to generate assembly for a file
src/sqlite3pp.cpp.s:
	$(MAKE) -f CMakeFiles/acc2taxid.dir/build.make CMakeFiles/acc2taxid.dir/src/sqlite3pp.cpp.s
	$(MAKE) -f CMakeFiles/alignments-prefilter-training.dir/build.make CMakeFiles/alignments-prefilter-training.dir/src/sqlite3pp.cpp.s
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/src/sqlite3pp.cpp.s
	$(MAKE) -f CMakeFiles/unittest_ncbitaxonomy.dir/build.make CMakeFiles/unittest_ncbitaxonomy.dir/src/sqlite3pp.cpp.s
.PHONY : src/sqlite3pp.cpp.s

src/taxonprediction.o: src/taxonprediction.cpp.o
.PHONY : src/taxonprediction.o

# target to build an object file
src/taxonprediction.cpp.o:
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/src/taxonprediction.cpp.o
.PHONY : src/taxonprediction.cpp.o

src/taxonprediction.i: src/taxonprediction.cpp.i
.PHONY : src/taxonprediction.i

# target to preprocess a source file
src/taxonprediction.cpp.i:
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/src/taxonprediction.cpp.i
.PHONY : src/taxonprediction.cpp.i

src/taxonprediction.s: src/taxonprediction.cpp.s
.PHONY : src/taxonprediction.s

# target to generate assembly for a file
src/taxonprediction.cpp.s:
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/src/taxonprediction.cpp.s
.PHONY : src/taxonprediction.cpp.s

src/taxontree.o: src/taxontree.cpp.o
.PHONY : src/taxontree.o

# target to build an object file
src/taxontree.cpp.o:
	$(MAKE) -f CMakeFiles/alignments-prefilter-training.dir/build.make CMakeFiles/alignments-prefilter-training.dir/src/taxontree.cpp.o
	$(MAKE) -f CMakeFiles/extract-fastacomment-ncbifield.dir/build.make CMakeFiles/extract-fastacomment-ncbifield.dir/src/taxontree.cpp.o
	$(MAKE) -f CMakeFiles/name-filter.dir/build.make CMakeFiles/name-filter.dir/src/taxontree.cpp.o
	$(MAKE) -f CMakeFiles/prediction2distances.dir/build.make CMakeFiles/prediction2distances.dir/src/taxontree.cpp.o
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/src/taxontree.cpp.o
	$(MAKE) -f CMakeFiles/rank-filter.dir/build.make CMakeFiles/rank-filter.dir/src/taxontree.cpp.o
	$(MAKE) -f CMakeFiles/unittest_ncbitaxonomy.dir/build.make CMakeFiles/unittest_ncbitaxonomy.dir/src/taxontree.cpp.o
.PHONY : src/taxontree.cpp.o

src/taxontree.i: src/taxontree.cpp.i
.PHONY : src/taxontree.i

# target to preprocess a source file
src/taxontree.cpp.i:
	$(MAKE) -f CMakeFiles/alignments-prefilter-training.dir/build.make CMakeFiles/alignments-prefilter-training.dir/src/taxontree.cpp.i
	$(MAKE) -f CMakeFiles/extract-fastacomment-ncbifield.dir/build.make CMakeFiles/extract-fastacomment-ncbifield.dir/src/taxontree.cpp.i
	$(MAKE) -f CMakeFiles/name-filter.dir/build.make CMakeFiles/name-filter.dir/src/taxontree.cpp.i
	$(MAKE) -f CMakeFiles/prediction2distances.dir/build.make CMakeFiles/prediction2distances.dir/src/taxontree.cpp.i
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/src/taxontree.cpp.i
	$(MAKE) -f CMakeFiles/rank-filter.dir/build.make CMakeFiles/rank-filter.dir/src/taxontree.cpp.i
	$(MAKE) -f CMakeFiles/unittest_ncbitaxonomy.dir/build.make CMakeFiles/unittest_ncbitaxonomy.dir/src/taxontree.cpp.i
.PHONY : src/taxontree.cpp.i

src/taxontree.s: src/taxontree.cpp.s
.PHONY : src/taxontree.s

# target to generate assembly for a file
src/taxontree.cpp.s:
	$(MAKE) -f CMakeFiles/alignments-prefilter-training.dir/build.make CMakeFiles/alignments-prefilter-training.dir/src/taxontree.cpp.s
	$(MAKE) -f CMakeFiles/extract-fastacomment-ncbifield.dir/build.make CMakeFiles/extract-fastacomment-ncbifield.dir/src/taxontree.cpp.s
	$(MAKE) -f CMakeFiles/name-filter.dir/build.make CMakeFiles/name-filter.dir/src/taxontree.cpp.s
	$(MAKE) -f CMakeFiles/prediction2distances.dir/build.make CMakeFiles/prediction2distances.dir/src/taxontree.cpp.s
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/src/taxontree.cpp.s
	$(MAKE) -f CMakeFiles/rank-filter.dir/build.make CMakeFiles/rank-filter.dir/src/taxontree.cpp.s
	$(MAKE) -f CMakeFiles/unittest_ncbitaxonomy.dir/build.make CMakeFiles/unittest_ncbitaxonomy.dir/src/taxontree.cpp.s
.PHONY : src/taxontree.cpp.s

unittest_ncbitaxonomy.o: unittest_ncbitaxonomy.cpp.o
.PHONY : unittest_ncbitaxonomy.o

# target to build an object file
unittest_ncbitaxonomy.cpp.o:
	$(MAKE) -f CMakeFiles/unittest_ncbitaxonomy.dir/build.make CMakeFiles/unittest_ncbitaxonomy.dir/unittest_ncbitaxonomy.cpp.o
.PHONY : unittest_ncbitaxonomy.cpp.o

unittest_ncbitaxonomy.i: unittest_ncbitaxonomy.cpp.i
.PHONY : unittest_ncbitaxonomy.i

# target to preprocess a source file
unittest_ncbitaxonomy.cpp.i:
	$(MAKE) -f CMakeFiles/unittest_ncbitaxonomy.dir/build.make CMakeFiles/unittest_ncbitaxonomy.dir/unittest_ncbitaxonomy.cpp.i
.PHONY : unittest_ncbitaxonomy.cpp.i

unittest_ncbitaxonomy.s: unittest_ncbitaxonomy.cpp.s
.PHONY : unittest_ncbitaxonomy.s

# target to generate assembly for a file
unittest_ncbitaxonomy.cpp.s:
	$(MAKE) -f CMakeFiles/unittest_ncbitaxonomy.dir/build.make CMakeFiles/unittest_ncbitaxonomy.dir/unittest_ncbitaxonomy.cpp.s
.PHONY : unittest_ncbitaxonomy.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... acc2taxid"
	@echo "... alignments-prefilter"
	@echo "... alignments-prefilter-training"
	@echo "... edit_cache"
	@echo "... extract-fastacomment-ncbifield"
	@echo "... name-filter"
	@echo "... prediction-error"
	@echo "... prediction2distances"
	@echo "... predictor"
	@echo "... rank-filter"
	@echo "... rebuild_cache"
	@echo "... unittest_ncbitaxonomy"
	@echo "... acc2taxid.o"
	@echo "... acc2taxid.i"
	@echo "... acc2taxid.s"
	@echo "... alignments-prefilter-training.o"
	@echo "... alignments-prefilter-training.i"
	@echo "... alignments-prefilter-training.s"
	@echo "... alignments-prefilter.o"
	@echo "... alignments-prefilter.i"
	@echo "... alignments-prefilter.s"
	@echo "... extract-fastacomment-ncbifield.o"
	@echo "... extract-fastacomment-ncbifield.i"
	@echo "... extract-fastacomment-ncbifield.s"
	@echo "... name-filter.o"
	@echo "... name-filter.i"
	@echo "... name-filter.s"
	@echo "... prediction-error.o"
	@echo "... prediction-error.i"
	@echo "... prediction-error.s"
	@echo "... prediction2distances.o"
	@echo "... prediction2distances.i"
	@echo "... prediction2distances.s"
	@echo "... predictor.o"
	@echo "... predictor.i"
	@echo "... predictor.s"
	@echo "... rank-filter.o"
	@echo "... rank-filter.i"
	@echo "... rank-filter.s"
	@echo "... src/accessconv.o"
	@echo "... src/accessconv.i"
	@echo "... src/accessconv.s"
	@echo "... src/alignmentrecord.o"
	@echo "... src/alignmentrecord.i"
	@echo "... src/alignmentrecord.s"
	@echo "... src/ncbidata.o"
	@echo "... src/ncbidata.i"
	@echo "... src/ncbidata.s"
	@echo "... src/sqlite3pp.o"
	@echo "... src/sqlite3pp.i"
	@echo "... src/sqlite3pp.s"
	@echo "... src/taxonprediction.o"
	@echo "... src/taxonprediction.i"
	@echo "... src/taxonprediction.s"
	@echo "... src/taxontree.o"
	@echo "... src/taxontree.i"
	@echo "... src/taxontree.s"
	@echo "... unittest_ncbitaxonomy.o"
	@echo "... unittest_ncbitaxonomy.i"
	@echo "... unittest_ncbitaxonomy.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

