#!/usr/bin/env python
# dirty Python 2.7 implementation without dependencies

from sys import argv, stdout, stderr, exit
import fileinput
import signal

signal.signal(signal.SIGPIPE, signal.SIG_DFL)

data = fileinput.input()

# eat white space at beginning
for line in data:
	if line[0] == ">":
		line_outer = line
		break

seen = set()  # make sure that new identifiers are unique

# convert comment lines and leave rest untouched
while line_outer:
	short_ident = line_outer[1:].split(None, 1)[0]
	if short_ident in seen:
		stderr.write("Error: duplicate FASTA entry '%s'.\n" % short_ident)
		exit(1)
	print ">%s" % (short_ident)
	seen.add(short_ident)
	line_outer = None
	for line in data:
		if line[0] == ">":
			line_outer = line
			break
		stdout.write(line)
